"""Compare anomaly models on generated data and explicit realistic fixtures.

Usage: python evaluate.py. Metrics are diagnostic only because generated labels
and generated training data share assumptions; this is not a real-world benchmark.
"""
import numpy as np
from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.svm import OneClassSVM
from decision import ANOMALY_HOLD_THRESHOLD, ANOMALY_REJECT_THRESHOLD

from features import FEATURE_NAMES, session_to_features
from synthetic_data import generate_abuse_sessions, generate_normal_sessions


def realistic_fixtures():
    rows = [
        ("typical_cakely", [1, 18, 1, 1], 0),
        ("slow_customer", [0, 420, 1, 1], 0),
        ("occasional_shared_device", [1, 70, 2, 1], 0),
        ("coupon_burst", [9, 2, 4, 2], 1),
        ("account_farming", [5, 8, 7, 4], 1),
        ("address_farming", [5, 10, 4, 7], 1),
    ]
    return np.asarray([row[1] for row in rows], dtype=float), np.asarray([row[2] for row in rows]), [row[0] for row in rows]


def _evaluate(name, estimator, train, test, labels, hold_threshold, reject_threshold):
    estimator.fit(train)
    scores = estimator.decision_function(test).reshape(-1)
    predicted = (scores < hold_threshold).astype(int)
    print(f"\n{name}")
    print("confusion_matrix [normal, abuse]:")
    print(confusion_matrix(labels, predicted, labels=[0, 1]))
    print(classification_report(labels, predicted, labels=[0, 1], target_names=["normal", "abuse"], zero_division=0))
    print(f"thresholds: hold={hold_threshold:.4f}, reject={reject_threshold:.4f}; "
          f"rejects={(scores < reject_threshold).sum()}, holds={((scores < hold_threshold) & (scores >= reject_threshold)).sum()}")


def main():
    train = generate_normal_sessions(n=5000)
    abuse = generate_abuse_sessions(n=500)
    generated = np.vstack([generate_normal_sessions(n=500, seed=84), abuse])
    generated_labels = np.r_[np.zeros(500, dtype=int), np.ones(len(abuse), dtype=int)]
    fixture_x, fixture_y, fixture_names = realistic_fixtures()
    # Apply the same scoring clipping used by production.
    generated = np.vstack([session_to_features(dict(zip(FEATURE_NAMES, row)))[0] for row in generated])
    fixture_x = np.vstack([session_to_features(dict(zip(FEATURE_NAMES, row)))[0] for row in fixture_x])
    print("Synthetic generated evaluation; labels are generated by construction.")
    for name, model in [
        ("Isolation Forest", IsolationForest(contamination=0.03, random_state=42)),
        ("One-Class SVM", OneClassSVM(nu=0.03, gamma="scale")),
    ]:
        model.fit(train)
        normal_scores = model.decision_function(train).reshape(-1)
        if name == "Isolation Forest":
            hold, reject = ANOMALY_HOLD_THRESHOLD, ANOMALY_REJECT_THRESHOLD
        else:
            # SVM scores have a different scale. Derive equivalent tail cutoffs
            # from normal training scores rather than reusing IF score values.
            hold, reject = np.quantile(normal_scores, [0.03, 0.01])
        _evaluate(name + " / generated set", model, train, generated, generated_labels, hold, reject)
        _evaluate(name + " / realistic hand-written fixtures", model, train, fixture_x, fixture_y, hold, reject)
        scores = model.decision_function(fixture_x).reshape(-1)
        print("fixture_decisions:", dict(zip(fixture_names, ["reject" if s < reject else "hold" if s < hold else "accept" for s in scores])))


if __name__ == "__main__":
    main()
