-- The Cakely/Supabase schema is the source of truth for this component.
-- No tables are created here. The service writes to the existing:
--   transaction_events(event_id, event_type, user_id, order_id, metadata)
--   products(id, name, base_price, active)
-- No audit_log or rulelock_* tables are required by this component.
-- Configure SUPABASE_URL and SUPABASE_SECRET_KEY in data-collection/.env.
