-- The Cakely/Supabase schema is the source of truth for this component.
-- RuleLock reads the existing products table and writes transaction_events.
-- Apply migrations/2026-10-03_rulelock_review_idempotency.sql and
-- migrations/2026-10-03_rulelock_audit_log.sql manually for review uniqueness
-- and immutable audit records. Configure Supabase secrets in the environment.
